### ISSUE TITLE
Enforce label selectors on secrets and configmaps

### ISSUE THREAD

**Issue by sthaha** [rhobs/observability-operator#260]
One of the features of Prometheus Operator is to run a reconcile loop when any of the secrets, configmaps (that may or may not be) used by ServiceMonitor or other first level CRs changes. In order to do this PO, watches **all** config maps and **secrets** this increases the memory requirement of the operator. 

In upstream PO, there is an on going effort to reduce the memory needed but meanwhile, in ObO if we require secrets and configmaps to have  "special"  label ( e.g. `"po.monitoring.rhobs/watch: true"` ), then PO shouldn't consume as much memory as it does now. This will of course need to be documented, brought to user's attention  since this isn't the default behaviour. 

WDYT, @simonpasquier @jan--f @tremes

**Comment by tremes** [comment]
@sthaha So only a configmap or secret  with this label will be watched by the PO right? I guess this label needs to be  propagated to the PO right? Does it require some PO's updates? What would be the impact of this change to the existing OBO installations?

I was just thinking whether exclude (maybe on the namespace level?) wouldn't be better (instead of this include).

**Comment by simonpasquier** [comment]
IIUC @sthaha means that the "special" label would be passed to the operator's `--secret-field-selector` CLI arg. After looking more into it, I'm afraid that it wouldn't work as-is because the input is a field selector and not a label selector.
See https://github.com/prometheus-operator/prometheus-operator/issues/3298 for the context but the initial use case was to filter out secrets of type `helm.sh/release.v1`.

**Comment by simonpasquier** [comment]
Also it wouldn't apply to configmaps.

**Comment by simonpasquier** [comment]
@sthaha this can be closed now that https://github.com/prometheus-operator/prometheus-operator/issues/5410 is fixed and available in the next operator release?

**Comment by sthaha** [comment]
Thanks Simon 🙇
