### ISSUE TITLE
GH Release workflow isn't creating candidate releases

### ISSUE THREAD

**Issue by sthaha** [rhobs/observability-operator#302]
https://github.com/rhobs/observability-operator/actions/workflows/olm-candidate.yaml isn't creating candidate release and must be fixed. Thanks @jan--f and @lihongyan1  for noticing.

**Comment by lihongyan1** [comment]
From 0.0.17-rc and after [PR](https://github.com/rhobs/observability-operator/commit/380d907882ca07ab466ae2ff7b2361f00e2ffb74), no candidate release is delivered, workflow [olm-candidate.yaml ](https://github.com/rhobs/observability-operator/blob/main/.github/workflows/olm-candidate.yaml) has never been executed since then.

**Comment by lihongyan1** [comment]
https://github.com/rhobs/observability-operator/blob/main/.github/workflows/release.yaml failed to trigger https://github.com/rhobs/observability-operator/actions/workflows/olm-candidate.yaml

**Comment by lihongyan1** [comment]
Fixed with PR, close the issue
